Repository wasmerio/wasmer, pull requests merged in 2019-05, with the labels that each got.

#411 doc(readme) Add `ruby-ext-wasm`
  README.md
Labels: 📚 documentation

#420 Add wapm section to README
  README.md
Labels: 🎉 enhancement

#429 implement some FS operations for rsign2
  CHANGELOG.md
  lib/wasi/src/syscalls/mod.rs
Labels: 📦 lib-wasi

#445 Better README.md link target for "WASI"
  README.md
Labels: 🎉 enhancement, 📚 documentation

#446 apply base path update to wasi::path_filestat_get
  lib/wasi/src/syscalls/mod.rs
Labels: 📦 lib-wasi

#474 fix(runtime-c-api) Set the install name of the dylib to `@rpath`.
  .circleci/config.yml
Labels: 🐞 bug, 📦 lib-runtime-c-api
