Repository wasmerio/wasmer, pull requests merged in 2020-05, with the labels that each got.

#1427 Make func clonable
  lib/runtime-core/src/typed_func.rs
Labels: 📦 lib-runtime-core

#1439 feat(interface-types) Move to its own repository
  CHANGELOG.md
  Cargo.toml
  Makefile
  lib/interface-types/Cargo.toml
  lib/interface-types/README.md
  lib/interface-types/src/ast.rs
  lib/interface-types/src/decoders/binary.rs
  lib/interface-types/src/decoders/mod.rs
  lib/interface-types/src/decoders/wat.rs
  lib/interface-types/src/encoders/binary.rs
  lib/interface-types/src/encoders/mod.rs
  lib/interface-types/src/encoders/wat.rs
  lib/interface-types/src/errors.rs
  lib/interface-types/src/interpreter/instructions/argument_get.rs
  lib/interface-types/src/interpreter/instructions/call_core.rs
  lib/interface-types/src/interpreter/instructions/mod.rs
  lib/interface-types/src/interpreter/instructions/numbers.rs
  lib/interface-types/src/interpreter/instructions/records.rs
  lib/interface-types/src/interpreter/instructions/strings.rs
  lib/interface-types/src/interpreter/mod.rs
  lib/interface-types/src/interpreter/stack.rs
  lib/interface-types/src/interpreter/wasm/mod.rs
  lib/interface-types/src/interpreter/wasm/structures.rs
  lib/interface-types/src/lib.rs
  lib/interface-types/src/macros.rs
  lib/interface-types/src/serde/de.rs
  lib/interface-types/src/serde/mod.rs
  lib/interface-types/src/serde/ser.rs
  lib/interface-types/src/types.rs
  lib/interface-types/src/values.rs
  lib/interface-types/src/vec1.rs
  lib/interface-types/tests/binary.rs
Labels: 🎉 enhancement

#1447 doc(readme) Add Java in the language integrations list
  README.md
  assets/languages/c.svg
  assets/languages/cpp.svg
  assets/languages/csharp.svg
  assets/languages/go.svg
  assets/languages/java.svg
  assets/languages/js.svg
  assets/languages/php.svg
  assets/languages/python.svg
  assets/languages/ruby.svg
  assets/languages/rust.svg
Labels: 🎉 enhancement, 📚 documentation
