Repository wasmerio/wasmer, pull requests merged in 2020-11, with the labels that each got.

#1783 feat(c-api) Handle initialized but empty results in `wasm_func_call`
  CHANGELOG.md
  lib/c-api/src/wasm_c_api/externals/function.rs
  lib/c-api/src/wasm_c_api/macros.rs
  lib/c-api/tests/wasm_c_api/CMakeLists.txt
Labels: 🎉 enhancement, 📦 lib-c-api, 🧪 tests

#1785 Add more examples on the Rust API
  Cargo.toml
  examples/README.md
  examples/early_exit.rs
  examples/errors.rs
  examples/exports_function.rs
  examples/exports_global.rs
  examples/imports_function.rs
  examples/imports_function_env.rs
  examples/instance.rs
  examples/memory.rs
  examples/tunables_limit_memory.rs
Labels: 🎉 enhancement, 📚 documentation

#1812 fix(ci): Test and then rebuild the C API
  .github/workflows/main.yaml
Labels: 🐞 bug, 🧪 tests

#1767 feat(makefile) Add more `build-capi-*` targets
  Makefile
  lib/c-api/wasmer_wasm.h
Labels: 🎉 enhancement, 📦 lib-c-api, 📦 lib-compiler, 📦 lib-compiler-cranelift, 📦 lib-compiler-llvm, 📦 lib-compiler-singlepass, 📦 lib-engine, 📦 lib-engine-jit, 📦 lib-engine-native, 📦 lib-engine-object-file, 🤖 bot

#1795 test(c-api) Introduce inline-c-rs, and use it!
  Cargo.lock
  Makefile
  lib/c-api/Cargo.toml
  lib/c-api/build.rs
  lib/c-api/doc/deprecated/doxyfile
  lib/c-api/doc/wasm_c_api/.empty
  lib/c-api/src/wasm_c_api/externals/function.rs
  lib/c-api/src/wasm_c_api/externals/global.rs
  lib/c-api/src/wasm_c_api/externals/memory.rs
  lib/c-api/src/wasm_c_api/externals/table.rs
  lib/c-api/src/wasm_c_api/macros.rs
  lib/c-api/src/wasm_c_api/module.rs
  lib/c-api/src/wasm_c_api/types/export.rs
  lib/c-api/src/wasm_c_api/types/extern_.rs
  lib/c-api/src/wasm_c_api/types/function.rs
  lib/c-api/src/wasm_c_api/types/global.rs
  lib/c-api/src/wasm_c_api/types/memory.rs
  lib/c-api/src/wasm_c_api/types/table.rs
  lib/c-api/src/wasm_c_api/wat.rs
  lib/c-api/tests/wasmer_wasm.h
Labels: 🐞 bug, 📦 lib-c-api, 🧪 tests

#1809 fix(c-api) Remove memory leaks and address `TODO`s
  Cargo.lock
  lib/c-api/src/wasm_c_api/DEVELOPMENT.md
  lib/c-api/src/wasm_c_api/engine.rs
  lib/c-api/src/wasm_c_api/externals/function.rs
  lib/c-api/src/wasm_c_api/externals/global.rs
  lib/c-api/src/wasm_c_api/externals/memory.rs
  lib/c-api/src/wasm_c_api/externals/mod.rs
  lib/c-api/src/wasm_c_api/externals/table.rs
  lib/c-api/src/wasm_c_api/instance.rs
  lib/c-api/src/wasm_c_api/module.rs
  lib/c-api/src/wasm_c_api/store.rs
  lib/c-api/src/wasm_c_api/trap.rs
  lib/c-api/src/wasm_c_api/types/export.rs
  lib/c-api/src/wasm_c_api/types/function.rs
  lib/c-api/src/wasm_c_api/types/global.rs
  lib/c-api/src/wasm_c_api/types/import.rs
  lib/c-api/src/wasm_c_api/types/memory.rs
  lib/c-api/src/wasm_c_api/types/table.rs
  lib/c-api/src/wasm_c_api/types/value.rs
  lib/c-api/src/wasm_c_api/value.rs
  lib/c-api/src/wasm_c_api/wasmer.rs
  lib/c-api/wasmer_wasm.h
Labels: 🐞 bug, 📚 documentation, 📦 lib-c-api, 🧪 tests

#1649 Add migration docs
  CHANGELOG.md
  docs/deps_dedup.dot
  docs/deps_dedup.svg
  docs/migration_to_1.0.0.md
Labels: 🎉 enhancement, 📚 documentation

#1764 Fix issue with `path_rename` moving down 1 directory
  CHANGELOG.md
  lib/wasi/src/syscalls/mod.rs
  tests/wasi-wast/README.md
  tests/wasi-wast/wasi/snapshot1/path_rename.wasm
  tests/wasi-wast/wasi/snapshot1/path_rename.wast
  tests/wasi-wast/wasi/tests/path_rename.rs
  tests/wasi-wast/wasi/unstable/path_rename.wasm
  tests/wasi-wast/wasi/unstable/path_rename.wast
Labels: 🐞 bug, 📦 lib-wasi

#1796 Make FunctionBodyPtr a thin pointer.
  lib/engine-jit/src/artifact.rs
  lib/engine-jit/src/engine.rs
  lib/engine-jit/src/link.rs
  lib/engine-native/src/artifact.rs
  lib/engine-object-file/src/artifact.rs
  lib/engine/src/trap/frame_info.rs
  lib/engine/src/trap/mod.rs
  lib/vm/src/lib.rs
  tests/lib/engine-dummy/src/artifact.rs
Labels: 🎉 enhancement, 📦 lib-engine, 📦 lib-engine-jit, 📦 lib-engine-object-file, 📦 lib-vm

#1821 doc(c-api) Fix links in `DEVELOPMENT.md`
  lib/c-api/src/wasm_c_api/DEVELOPMENT.md
Labels: 🐞 bug, 📚 documentation, 📦 lib-c-api

#1819 fix(ci): Regex correctly matches tags when doing release
  .github/workflows/main.yaml
Labels: 🎉 enhancement

#1820 test(api) Add more tests for the `.to_native` API
  lib/api/src/externals/function.rs
Labels: 🎉 enhancement, 📦 lib-api, 🧪 tests

#1822 fix(vm) Fix memory leak of `InstanceHandle`
  lib/api/src/instance.rs
  lib/compiler-cranelift/src/compiler.rs
  lib/compiler/src/translator/environ.rs
  lib/engine-jit/src/artifact.rs
  lib/engine-native/src/artifact.rs
  lib/engine-object-file/src/artifact.rs
  lib/vm/src/instance.rs
Labels: 🐞 bug, 📦 lib-api, 📦 lib-engine, 📦 lib-vm

#1828 feat(vm) Simplify pointer arithmetic by using existing helper methods
  lib/vm/src/instance.rs
Labels: 🎉 enhancement

#1827 feat(vm) Don't clone the export in `Instance::lookup`
  lib/vm/src/instance.rs
Labels: 🎉 enhancement, 📦 lib-vm

#1826 feat(api) Faster `Exports::from_iter`
  lib/api/src/exports.rs
Labels: 🎉 enhancement, 📦 lib-api

#1830 Bump CI Rust version to 1.47.0
  .github/workflows/benchmark.yaml
  .github/workflows/main.yaml
  CHANGELOG.md
Labels: 1.0, 🎉 enhancement

#1663 Make Function Env immutable
  CHANGELOG.md
  examples/imports_function_env.rs
  lib/api/Cargo.toml
  lib/api/src/externals/function.rs
  lib/api/src/externals/mod.rs
  lib/api/src/lib.rs
  lib/api/tests/externals.rs
  lib/c-api/src/deprecated/import/mod.rs
  lib/c-api/src/wasm_c_api/externals/function.rs
  lib/deprecated/runtime-core/Cargo.lock
  lib/deprecated/runtime-core/Cargo.toml
  lib/deprecated/runtime-core/src/typed_func.rs
  lib/deprecated/runtime-core/src/vm.rs
  lib/deprecated/runtime/Cargo.lock
  lib/emscripten/src/bitwise.rs
  lib/emscripten/src/emscripten_target.rs
  lib/emscripten/src/env/mod.rs
  lib/emscripten/src/env/unix/mod.rs
  lib/emscripten/src/env/windows/mod.rs
  lib/emscripten/src/errno.rs
  lib/emscripten/src/exception.rs
  lib/emscripten/src/exec.rs
  lib/emscripten/src/exit.rs
  lib/emscripten/src/inet.rs
  lib/emscripten/src/io/mod.rs
  lib/emscripten/src/io/unix.rs
  lib/emscripten/src/io/windows.rs
  lib/emscripten/src/jmp.rs
  lib/emscripten/src/lib.rs
  lib/emscripten/src/libc.rs
  lib/emscripten/src/linking.rs
  lib/emscripten/src/lock.rs
  lib/emscripten/src/math.rs
  lib/emscripten/src/memory.rs
  lib/emscripten/src/process.rs
  lib/emscripten/src/pthread.rs
  lib/emscripten/src/signal.rs
  lib/emscripten/src/syscalls/mod.rs
  lib/emscripten/src/syscalls/unix.rs
  lib/emscripten/src/syscalls/windows.rs
  lib/emscripten/src/time.rs
  lib/emscripten/src/ucontext.rs
  lib/emscripten/src/unistd.rs
  lib/emscripten/src/utils.rs
  lib/emscripten/src/varargs.rs
  lib/vm/src/instance.rs
  lib/wasi/src/lib.rs
  lib/wasi/src/syscalls/legacy/snapshot0.rs
  lib/wasi/src/syscalls/mod.rs
  tests/compilers/imports.rs
  tests/compilers/native_functions.rs
Labels: 1.0

#1831 ARM Silicon Support
  .github/workflows/main.yaml
  CHANGELOG.md
  Cargo.lock
  Makefile
  examples/engine_cross_compilation.rs
  lib/c-api/Cargo.toml
  lib/cli/src/commands/compile.rs
  lib/compiler-cranelift/Cargo.toml
  lib/compiler-cranelift/src/translator/unwind.rs
  lib/deprecated/runtime-core/Cargo.lock
  lib/deprecated/runtime/Cargo.lock
  lib/engine-native/src/artifact.rs
  lib/engine/src/resolver.rs
  lib/object/src/module.rs
  lib/vm/src/trap/traphandlers.rs
  lib/wasi/src/lib.rs
  lib/wasi/src/ptr.rs
  lib/wasi/src/syscalls/mod.rs
  lib/wasmer-types/Cargo.toml
  scripts/binary-name.sh
  tests/compilers/native_functions.rs
  tests/compilers/traps.rs
Labels: 1.0, 🎉 enhancement

#1843 Add "Hello World" example
  Cargo.toml
  examples/README.md
  examples/hello_world.rs
Labels: 🎉 enhancement, 📚 documentation

#1829 chore(ci): Use the new llvm-custom-builds
  .github/workflows/main.yaml
  Makefile
Labels: 🎉 enhancement

#1847 fix(compiler-singlepass) Fix future rustc error
  lib/compiler-singlepass/src/codegen_x64.rs
Labels: 🐞 bug, 📦 lib-compiler-singlepass

#1846 feat: Use the same version of `smallvec` everywhere
  Cargo.lock
  lib/compiler-cranelift/Cargo.toml
  lib/compiler-llvm/Cargo.toml
  lib/compiler-singlepass/Cargo.toml
  lib/compiler/Cargo.toml
Labels: 🎉 enhancement

#1848 chore: Update semver
  Cargo.lock
  lib/compiler-llvm/Cargo.toml
Labels: 1.0, dependencies, 🎉 enhancement

#1849 chore: Update object
  Cargo.lock
  lib/object/Cargo.toml
Labels: 1.0, dependencies, 🎉 enhancement

#1841 Disable closures as host functions for now + docs + tests
  CHANGELOG.md
  lib/api/src/externals/function.rs
  lib/deprecated/runtime-core/src/functional_api.rs
  tests/compilers/native_functions.rs
Labels: 1.0, 🎉 enhancement, 🐞 bug
