Repository wasmerio/wasmer, pull requests merged in 2020-08, with the labels that each got.

#1545 fix(deprecated) Fix doc links and formatting
  lib/deprecated/README.md
  lib/deprecated/runtime-core/CHANGES.md
  lib/deprecated/runtime-core/README.md
  lib/deprecated/runtime/README.md
Labels: 🐞 bug, 📚 documentation

#1562 fix(wasi) Replace an `unwrap` by an `expect`.
  lib/wasi/src/lib.rs
Labels: 🐞 bug, 📦 lib-wasi

#1558 feat(wasmer-types) Implement `NativeWasmType` for `u128`
  lib/wasmer-types/src/native.rs
Labels: 🎉 enhancement

#1581 fix(compiler-cranelift) Don't generate an empty `FrameTable` if function body inputs is empty
  lib/compiler-cranelift/src/compiler.rs
  lib/engine-jit/src/unwind/systemv.rs
Labels: 🐞 bug

#1566 Add support for WASI opening Unix special files
  CHANGELOG.md
  Cargo.lock
  lib/wasi/src/state/mod.rs
  tests/ignores.txt
  tests/wasi-wast/README.md
  tests/wasi-wast/wasi/snapshot1/unix_open_special_files.wasm
  tests/wasi-wast/wasi/snapshot1/unix_open_special_files.wast
  tests/wasi-wast/wasi/tests/unix_open_special_files.rs
  tests/wasi-wast/wasi/unstable/unix_open_special_files.wasm
  tests/wasi-wast/wasi/unstable/unix_open_special_files.wast
Labels: 🎉 enhancement, 📦 lib-wasi
